project_id = "gplyfkjmzlueerxhtotu"

[functions.register-with-invitation]
verify_jwt = false

[functions.create-test-users]
verify_jwt = false

[functions.send-reminder-email]
enabled = true
verify_jwt = true
import_map = "./functions/send-reminder-email/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-reminder-email/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-reminder-email/*.html" ]

[functions.create-calendar-event]
enabled = true
verify_jwt = true
import_map = "./functions/create-calendar-event/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-calendar-event/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-calendar-event/*.html" ]
